<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title><?php echo A('title', 'CoolestCars') ?></title>
		
		<?php foreach (A('styles', array()) as $style): ?>
		<link rel="stylesheet" type="text/css" href="<?php echo Atomik::appAsset($style) ?>" />
		<?php endforeach; ?>
		
		<script type="text/javascript">
      		function submit_form(whichOne){
        		var el;
       			if (whichOne == 2){
          			el = document.getElementById("rightcar");
        		} else if (whichOne == 1) {
          			el = document.getElementById("leftcar");
        		}
        		el.submit();
      		}
    	</script>
	</head>
	<body>
		<div id="title">
			<h1>CoolestCars</h1>
			<p><a href="<?php echo Atomik::url('home')?>" title="Home">Home</a> | Car ranking | Manufacturer ranking | Admin Login</p>
		</div>
		<div id="content">
			<?php echo $contentForLayout; ?>
		</div>
	</body>
</html>
