<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title><?php echo A('title', 'CoolestCars') ?></title>
		
		<?php foreach (A('styles', array()) as $style): ?>
		<link rel="stylesheet" type="text/css" href="<?php echo Atomik::appAsset($style) ?>" />
		<?php endforeach; ?>
		<?php foreach (A('scripts', array ()) as $script): ?>
		<script type="text/javascript" src="<?php echo Atomik::appAsset($script) ?>"></script>
		<?php endforeach; ?>
	</head>
	<body>
		<div id="title">
			<h1>CoolestCars</h1>
			<p>Click the car you think is cooler!</p>
			<p><?php if(isset($_SESSION['adminlogin'])){
					$loginname = $_SESSION['loginname'];
					echo "Logged in as $loginname ";
					echo '<a href="';
					echo Atomik::url('logout');
					echo '" title="Logout">(Logout)</a>';
				}else{
					echo "Not logged in";
				}?></p>
			<p><a href="<?php echo Atomik::url('home')?>" title="Home">Home</a> | <a href="<?php echo Atomik::url('carranking')?>" title "Car Ranking">Car ranking</a> | <a href="<?php echo Atomik::url('manufacturerranking')?>" title="Manufacturer Ranking">Manufacturer ranking</a> | <a href="<?php echo Atomik::url('login')?>" title="Login">Admin Login</a></p>
		</div>
		<p style="text-align: center;"><?php
			foreach(Atomik::get('flash:error') as $errormessage){
				echo $errormessage;
			}
			?></p>
		<div id="content">
			<?php echo $contentForLayout; ?>
		</div>
	</body>
</html>
