<div id="centeredcontent">
<!-- Not much to see here, just the home page for admin controls -->
<p style=>Welcome, <?php echo $_SESSION['loginname'] ?>!</p>
<a href="<?php echo Atomik::url('carmanagement')?>" title="Car management">Car management</a><br />
<a href="<?php echo Atomik::url('manufacturermanagement')?>" title="Manufacturer management">Manufacturer management</a><br />
<a href="<?php echo Atomik::url('loginmanagement')?>" title="Login management">Login management</a>
</div>
