<div id="centeredcontent">
<img src="<?php echo Atomik::asset('assets/images/'.$car['imagename'])?>">
<p>Name: <?php echo $car['cname'] ?></p>
<p>Manufacturer: <a href="<?php echo Atomik::url('manpage', array(manufacturerid => $car['manufacturerid']))?>" title="<?php echo $car['mname']?>"><?php echo $car['mname']?></a></p>
<p>Leave a comment below!</p>
<form name="carcomment" action="" method="post">
Nickname: <input type="text" name="usernickname" value="Anonymous"/><br />
Comment: <input type="text" name="commenttext" size="80" /><br />
<input type="hidden" name="carid" value="<?php echo $car['carid']?>" />
<input type="hidden" name="manufacturerid" value="<?php echo $car['manufacturerid']?>" />
<input type="submit" name="submit" value="Submit" />
</form>
<?php $this->printComments($comments)?>
</div>
