<!-- The main page of the application that displays the two cars user can click. The little
javascript function determines which form to send to the evaluator script -->
<div id="image1"><a href="#" onclick="submit_form(1); return false;"><img src="<?php echo Atomik::asset('assets/images/'.$leftcar['imagename']) ?>"></a>
<p><?php echo $leftcar['mname'].' '.$leftcar['cname'] ?></p></div>

<div id="image2"><a href="#" onclick="submit_form(2); return false;"><img src="<?php echo Atomik::asset('assets/images/'.$rightcar['imagename']) ?>"></a>
<p><?php echo $rightcar['mname'].' '.$rightcar['cname'] ?></p></div>
<?php $this->createForm("rightcar", $rightcar, $leftcar);
$this->createForm("leftcar", $leftcar, $rightcar) ?>
