
<script type="text/javascript">
    	function submit_form(whichOne){
        	var el;
       		if (whichOne == 2){
         		el = document.getElementById("rightcar");
        	} else if (whichOne == 1) {
          		el = document.getElementById("leftcar");
        	}
        	el.submit();
      	}
</script>
<div id="image1"><a href="#" onclick="submit_form(1); return false;"><img src="<?php echo Atomik::asset($leftcar['imagename']) ?>"></a>
<p><?php echo $leftcar['mname']; echo $leftcar['cname'] ?></p></div>

<div id="image2"><a href="#" onclick="submit_form(2); return false;"><img src="<?php echo Atomik::asset($rightcar['imagename']) ?>"></a>
<p><?php echo $rightcar['mname']; echo $rightcar['cname'] ?></p></div>

<?php $this->createForm("rightcar", $rightcar, $leftcar);
$this->createForm("leftcar", $leftcar, $rightcar) ?>
