<div id="title">
	<h1>CoolestCars</h1>
	Car ranking | Manufacturer ranking | Admin Login
</div>

<div id="image1"><a href="#" onclick="submit(vasen); return false;"><img src="<?php echo Atomik::asset('assets/images/1969_Dodge_Charger_green_F_small.jpg') ?>"></a>
<p>Dodge motherfucking charger</p></div>
<div id="image2"><a href="#" onclock="submit(oikea); return false;"><img src="<?php echo Atomik::asset('assets/images/Golf_Variant_small.jpg') ?>"></a>
<p>Another Dodge motherfucking charger</p></div>

<form id="leftcar" method="post" action="todo">
        <input type="hidden" value="lol" />
</form>
<form id="rightcar" method="post" action="todo">
	<input type="hidden" value="lol" />
</form>
